version: 0.2

env:
  variables:
    REPOSITORY_URI: "965080479351.dkr.ecr.ap-southeast-1.amazonaws.com/nginx-demo" 
    IMAGE_VERSION: "1.0" # Default version, this will be replaced during runtime.

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # - $(aws ecr get-login-password --region ap-southeast-1) | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Retrieving current image version...
      - export CURRENT_VERSION=$(aws ecr describe-images --repository-name nginx-demo --query "sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]" --output text || echo "0.0")
      - echo Current version: $CURRENT_VERSION
      - export IMAGE_VERSION=$(awk -F. -v OFS=. '{$NF += 1 ; print}' <<< "$CURRENT_VERSION")
      - echo Incremented version: $IMAGE_VERSION

  build:
    commands:
      - echo Building the Docker image with version $IMAGE_VERSION...
      - docker build -t nginx-demo:$IMAGE_VERSION .
      - docker tag nginx-demo:$IMAGE_VERSION $REPOSITORY_URI:$IMAGE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker image with version $IMAGE_VERSION...
      - docker push $REPOSITORY_URI:$IMAGE_VERSION
      - echo Build completed with image version $IMAGE_VERSION
