version: 0.2

env:
  variables:
    REPOSITORY_URI: "965080479351.dkr.ecr.ap-southeast-1.amazonaws.com/nginx-demo" 
    IMAGE_VERSION: "1.0" # Default version, this will be replaced during runtime.

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export DATE_VERSION=$(date +%Y%m%d)
      - export BUILD_NUMBER=$(aws ecr describe-images --repository-name $REPOSITORY_URI --query "length(imageDetails[?contains(imageTags[],\`$DATE_VERSION\`)])" --output text)
      - export NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
      - export IMAGE_VERSION="${DATE_VERSION}.${NEW_BUILD_NUMBER}"
      - echo "Building version $IMAGE_VERSION" 

  build:
    commands:
      - echo Building the Docker image with version $IMAGE_VERSION...
      - docker build -t nginx-demo:$IMAGE_VERSION .
      - docker tag nginx-demo:$IMAGE_VERSION $REPOSITORY_URI:$IMAGE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker image with version $IMAGE_VERSION...
      - docker push $REPOSITORY_URI:$IMAGE_VERSION
      - echo Build completed with image version $IMAGE_VERSION
